In [1]:
import numpy as np
import pandas as pd

In [20]:
df =  pd.read_csv('data/autoscout24-germany-dataset.csv')
df.head()

   mileage        make   model      fuel    gear offerType  price     hp  year
0   235000         BMW     316    Diesel  Manual      Used   6800  116.0  2011
1    92800  Volkswagen    Golf  Gasoline  Manual      Used   6877  122.0  2011
2   149300        SEAT    Exeo  Gasoline  Manual      Used   6900  160.0  2011
3    96200     Renault  Megane  Gasoline  Manual      Used   6950  110.0  2011
4   156000     Peugeot     308  Gasoline  Manual      Used   6950  156.0  2011

In [116]:
df.gear.unique()

array(['Manual', 'Automatic', nan, 'Semi-automatic'], dtype=object)

In [22]:
df.isnull().sum()

mileage        0
make           0
model        143
fuel           0
gear         182
offerType      0
price          0
hp            29
year           0
dtype: int64

In [23]:
df2 = df.dropna()

In [24]:
df2.isnull().sum()

mileage      0
make         0
model        0
fuel         0
gear         0
offerType    0
price        0
hp           0
year         0
dtype: int64

In [25]:
df2.groupby('fuel')['fuel'].agg('count')

fuel
-/- (Fuel)              22
CNG                    116
Diesel               15178
Electric               661
Electric/Diesel         53
Electric/Gasoline     1146
Ethanol                  2
Gasoline             28720
Hydrogen                 1
LPG                    125
Others                  47
Name: fuel, dtype: int64

In [15]:
#df2 =  df[df["fuel"].isin(["-/- (Fuel) ","Others"])]
#df2

,mileage,make,model,fuel,gear,offerType,price,hp,year
3001,50150,Toyota,Verso-S,Others,Manual,Used,9450,99.0,2015
3133,49,Fiat,500,Others,Manual,Pre-registered,14190,69.0,2021
4513,53750,Hyundai,i10,Others,Manual,Used,6880,69.0,2014
4514,53750,Hyundai,i10,Others,Manual,Used,6880,69.0,2014
4860,800,Fiat,500,Others,Manual,Pre-registered,14490,69.0,2021
4868,49,Fiat,500,Others,Manual,Pre-registered,14989,69.0,2021
5219,43400,Toyota,Aygo,Others,Manual,Used,8584,72.0,2018
6544,1500,Renault,Clio,Others,Manual,Demonstration,15580,72.0,2021
7221,119076,Renault,Clio,Others,Manual,Used,5990,73.0,2013
8087,87051,Toyota,Yaris,Others,Automatic,Used,10200,101.0,2014
8936,129000,Peugeot,208,Others,Manual,Used,6750,82.0,2014
11796,12,Hyundai,i20,Others,Manual,Pre-registered,13990,84.0,2021
13280,1250,Renault,Clio,Others,Manual,Pre-registered,16990,91.0,2021
13528,28290,Volkswagen,Polo,Others,Automatic,Used,12990,90.0,2012
13792,60000,Volkswagen,Golf Variant,Others,Manual,Used,12950,110.0,2015
14526,21217,Opel,Astra,Others,Manual,Used,15790,105.0,2019
14534,13716,Opel,Corsa,Others,Manual,Used,15945,101.0,2020
16041,10,Toyota,Aygo,Others,Manual,Pre-registered,9960,72.0,2021
16235,28071,Opel,Mokka X,Others,Manual,Used,15990,140.0,2019
16645,36479,Toyota,Yaris,Others,Automatic,Used,13590,101.0,2018
16758,66558,Ford,Focus,Others,Manual,Used,10880,125.0,2013
18249,114500,Toyota,Avensis,Others,Manual,Used,8900,147.0,2012
19504,48700,Opel,Mokka,Others,Manual,Used,14290,140.0,2015
19576,28071,Opel,Mokka X,Others,Manual,Used,15990,140.0,2019
19662,206000,BMW,320,Others,Manual,Used,6900,163.0,2012
19886,68650,Toyota,Verso,Others,Manual,Used,11550,147.0,2012
20573,82918,Volvo,V60,Others,Automatic,Used,16500,150.0,2016
24047,89733,Audi,A4,Others,Automatic,Used,23980,170.0,2018
29474,55000,Toyota,Auris,Others,Manual,Used,11760,116.0,2016
31810,113962,Ford,Focus,Others,Manual,Used,7990,101.0,2015
31936,1500,Toyota,Highlander,Others,Automatic,Demonstration,56990,247.0,2021
31943,49,Fiat,500,Others,Manual,Pre-registered,14490,69.0,2021
33601,42450,Toyota,Aygo,Others,Manual,Used,7900,69.0,2018
33652,10,Toyota,Aygo,Others,Manual,Pre-registered,10550,72.0,2021
40839,34317,Renault,Twingo,Others,Manual,Demonstration,8990,90.0,2017
42315,50946,Renault,ZOE,Others,Automatic,Used,12990,92.0,2018
42389,45502,Opel,Astra,Others,Manual,Used,13590,125.0,2018
42419,21990,SEAT,Mii,Others,Manual,Used,8229,68.0,2018
42624,47999,Renault,Koleos,Others,Manual,Demonstration,23790,177.0,2018
43306,27000,SEAT,Ibiza,Others,Manual,Used,8950,90.0,2019
43392,1590,Renault,Clio,Others,Manual,Demonstration,13190,90.0,2019
43688,17386,Skoda,Octavia,Others,Automatic,Used,18290,131.0,2019
43924,6757,Audi,A5,Others,Automatic,Used,30937,170.0,2019
43956,41948,Skoda,Kodiaq,Others,Automatic,Used,32990,190.0,2019
44873,1873,Fiat,500C,Others,Manual,Used,15900,71.0,2020
45530,10,Renault,Clio,Others,Manual,Demonstration,15555,101.0,2021
45534,10,Renault,Clio,Others,Manual,Demonstration,15777,101.0,2021

In [16]:
df2.shape

(47, 9)

In [26]:
df3 =df2[~df2["fuel"].isin(["-/- (Fuel) ","Others"])]
df3.head()

   mileage        make   model      fuel    gear offerType  price     hp  year
0   235000         BMW     316    Diesel  Manual      Used   6800  116.0  2011
1    92800  Volkswagen    Golf  Gasoline  Manual      Used   6877  122.0  2011
2   149300        SEAT    Exeo  Gasoline  Manual      Used   6900  160.0  2011
3    96200     Renault  Megane  Gasoline  Manual      Used   6950  110.0  2011
4   156000     Peugeot     308  Gasoline  Manual      Used   6950  156.0  2011

In [28]:
df3.shape

(46024, 9)

In [29]:
df3.groupby('offerType')['offerType'].agg('count')

offerType
Demonstration      2344
Employee's car     1117
New                  13
Pre-registered     2760
Used              39790
Name: offerType, dtype: int64

In [30]:
df4 = df3[df3["offerType"]!="Employee's car"]
df4.head()

   mileage        make   model      fuel    gear offerType  price     hp  year
0   235000         BMW     316    Diesel  Manual      Used   6800  116.0  2011
1    92800  Volkswagen    Golf  Gasoline  Manual      Used   6877  122.0  2011
2   149300        SEAT    Exeo  Gasoline  Manual      Used   6900  160.0  2011
3    96200     Renault  Megane  Gasoline  Manual      Used   6950  110.0  2011
4   156000     Peugeot     308  Gasoline  Manual      Used   6950  156.0  2011

In [33]:
df4.describe()

            mileage         price            hp          year
count  4.490700e+04  4.490700e+04  44907.000000  44907.000000
mean   7.277780e+04  1.622015e+04    132.220144   2015.909680
std    6.247094e+04  1.903409e+04     74.710737      3.127032
min    0.000000e+00  1.100000e+03      1.000000   2011.000000
25%    2.210000e+04  7.450000e+03     86.000000   2013.000000
50%    6.208000e+04  1.098000e+04    116.000000   2016.000000
75%    1.068345e+05  1.885000e+04    150.000000   2019.000000
max    1.111111e+06  1.199900e+06    850.000000   2021.000000

In [81]:
df5 = df4[df4["price"]<=500000]
df5

,mileage,make,model,fuel,gear,offerType,price,hp,year
0,235000,BMW,316,Diesel,Manual,Used,6800,116.0,2011
1,92800,Volkswagen,Golf,Gasoline,Manual,Used,6877,122.0,2011
2,149300,SEAT,Exeo,Gasoline,Manual,Used,6900,160.0,2011
3,96200,Renault,Megane,Gasoline,Manual,Used,6950,110.0,2011
4,156000,Peugeot,308,Gasoline,Manual,Used,6950,156.0,2011
...,...,...,...,...,...,...,...,...,...
46400,99,Fiat,500,Electric/Gasoline,Manual,Pre-registered,12990,71.0,2021
46401,99,Fiat,500,Electric/Gasoline,Manual,Pre-registered,12990,71.0,2021
46402,99,Fiat,500,Electric/Gasoline,Manual,Pre-registered,12990,71.0,2021
46403,99,Fiat,500,Electric/Gasoline,Manual,Pre-registered,12990,71.0,2021
46404,99,Fiat,500,Electric/Gasoline,Manual,Pre-registered,12990,71.0,2021

In [82]:
df5.columns.tolist()

['mileage',
 'make',
 'model',
 'fuel',
 'gear',
 'offerType',
 'price',
 'hp',
 'year']

In [39]:
df5.describe()

            mileage          price            hp          year
count  4.490400e+04   44904.000000  44904.000000  44904.000000
mean   7.278265e+04   16162.569971    132.183658   2015.909518
std    6.247021e+04   17585.115751     74.577665      3.127064
min    0.000000e+00    1100.000000      1.000000   2011.000000
25%    2.210000e+04    7450.000000     86.000000   2013.000000
50%    6.208800e+04   10980.000000    116.000000   2016.000000
75%    1.068515e+05   18842.500000    150.000000   2019.000000
max    1.111111e+06  499800.000000    850.000000   2021.000000

In [89]:
df6 =  df5.drop(['hp'], axis='columns')
df6.head()

   mileage        make   model      fuel    gear offerType  price  year
0   235000         BMW     316    Diesel  Manual      Used   6800  2011
1    92800  Volkswagen    Golf  Gasoline  Manual      Used   6877  2011
2   149300        SEAT    Exeo  Gasoline  Manual      Used   6900  2011
3    96200     Renault  Megane  Gasoline  Manual      Used   6950  2011
4   156000     Peugeot     308  Gasoline  Manual      Used   6950  2011

In [90]:
df6.columns.tolist()

['mileage', 'make', 'model', 'fuel', 'gear', 'offerType', 'price', 'year']

In [94]:
dummies = pd.get_dummies(df6, prefix=['make','model','fuel','gear','offerType'],drop_first=True)
dummies

,mileage,price,year,make_Aixam,make_Alfa,make_Alpina,make_Alpine,make_Aston,make_Audi,make_BMW,...,fuel_Electric/Gasoline,fuel_Ethanol,fuel_Gasoline,fuel_Hydrogen,fuel_LPG,gear_Manual,gear_Semi-automatic,offerType_New,offerType_Pre-registered,offerType_Used
0,235000,6800,2011,False,False,False,False,False,False,True,...,False,False,False,False,False,True,False,False,False,True
1,92800,6877,2011,False,False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,True
2,149300,6900,2011,False,False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,True
3,96200,6950,2011,False,False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,True
4,156000,6950,2011,False,False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46400,99,12990,2021,False,False,False,False,False,False,False,...,True,False,False,False,False,True,False,False,True,False
46401,99,12990,2021,False,False,False,False,False,False,False,...,True,False,False,False,False,True,False,False,True,False
46402,99,12990,2021,False,False,False,False,False,False,False,...,True,False,False,False,False,True,False,False,True,False
46403,99,12990,2021,False,False,False,False,False,False,False,...,True,False,False,False,False,True,False,False,True,False
46404,99,12990,2021,False,False,False,False,False,False,False,...,True,False,False,False,False,True,False,False,True,False

In [107]:
dummies.columns.tolist()

['mileage',
 'price',
 'year',
 'make_Aixam',
 'make_Alfa',
 'make_Alpina',
 'make_Alpine',
 'make_Aston',
 'make_Audi',
 'make_BMW',
 'make_Baic',
 'make_Bentley',
 'make_Brilliance',
 'make_Cadillac',
 'make_Chevrolet',
 'make_Chrysler',
 'make_Citroen',
 'make_Corvette',
 'make_Cupra',
 'make_DFSK',
 'make_DS',
 'make_Dacia',
 'make_Daihatsu',
 'make_Dodge',
 'make_Estrima',
 'make_FISKER',
 'make_Ferrari',
 'make_Fiat',
 'make_Ford',
 'make_Honda',
 'make_Hyundai',
 'make_Infiniti',
 'make_Isuzu',
 'make_Iveco',
 'make_Jaguar',
 'make_Jeep',
 'make_Kia',
 'make_Lada',
 'make_Lamborghini',
 'make_Lancia',
 'make_Land',
 'make_Lexus',
 'make_Ligier',
 'make_MINI',
 'make_Maserati',
 'make_Maybach',
 'make_Mazda',
 'make_McLaren',
 'make_Mercedes-Benz',
 'make_Microcar',
 'make_Mitsubishi',
 'make_Morgan',
 'make_Nissan',
 'make_Opel',
 'make_Others',
 'make_Peugeot',
 'make_Piaggio',
 'make_Polestar',
 'make_Porsche',
 'make_RAM',
 'make_Renault',
 'make_Rolls-Royce',
 'make_SEAT',
 'make_Skoda',
 'make_SsangYong',
 'make_Subaru',
 'make_Suzuki',
 'make_Tesla',
 'make_Toyota',
 'make_Volkswagen',
 'make_Volvo',
 'make_Zhidou',
 'make_smart',
 'model_108',
 'model_114',
 'model_116',
 'model_118',
 'model_120',
 'model_123',
 'model_124 Spider',
 'model_125',
 'model_135',
 'model_140',
 'model_1500',
 'model_2',
 'model_2008',
 'model_206',
 'model_207',
 'model_208',
 'model_214',
 'model_216',
 'model_218',
 'model_220',
 'model_225',
 'model_230',
 'model_240',
 'model_250',
 'model_3',
 'model_3-Wheeler',
 'model_300',
 'model_3008',
 'model_300C',
 'model_301',
 'model_308',
 'model_316',
 'model_318',
 'model_320',
 'model_323',
 'model_325',
 'model_328',
 'model_330',
 'model_335',
 'model_340',
 'model_370Z',
 'model_4008',
 'model_407',
 'model_418',
 'model_420',
 'model_428',
 'model_430',
 'model_435',
 'model_440',
 'model_458',
 'model_488',
 'model_5',
 'model_500',
 'model_5008',
 'model_500C',
 'model_500L',
 'model_500X',
 'model_500e',
 'model_508',
 'model_518',
 'model_520',
 'model_523',
 'model_525',
 'model_528',
 'model_530',
 'model_535',
 'model_540',
 'model_550',
 'model_570S',
 'model_595',
 'model_595 Competizione',
 'model_595 Turismo',
 'model_595C',
 'model_6',
 'model_600LT',
 'model_630',
 'model_640',
 'model_650',
 'model_675LT',
 'model_695',
 'model_720S',
 'model_730',
 'model_740',
 'model_750',
 'model_760',
 'model_807',
 'model_812',
 'model_840',
 'model_911',
 'model_991',
 'model_992',
 'model_997',
 'model_A 160',
 'model_A 180',
 'model_A 200',
 'model_A 220',
 'model_A 250',
 'model_A 35 AMG',
 'model_A 45 AMG',
 'model_A1',
 'model_A110',
 'model_A3',
 'model_A4',
 'model_A4 allroad',
 'model_A5',
 'model_A6',
 'model_A6 allroad',
 'model_A7',
 'model_A8',
 'model_AMG GT',
 'model_ASX',
 'model_ATS',
 'model_Accord',
 'model_Adam',
 'model_Agila',
 'model_Alaskan',
 'model_Alhambra',
 'model_Alpine A110',
 'model_Altea',
 'model_Altea XL',
 'model_Alto',
 'model_Amarok',
 'model_Ampera',
 'model_Antara',
 'model_Ape',
 'model_Arkana',
 'model_Arona',
 'model_Arteon',
 'model_Aspen',
 'model_Astra',
 'model_Ateca',
 'model_Auris',
 'model_Automobiles DS 3',
 'model_Automobiles DS 3 Crossback',
 'model_Automobiles DS 4',
 'model_Automobiles DS 5',
 'model_Automobiles DS 7 Crossback',
 'model_Avensis',
 'model_Aventador',
 'model_Aveo',
 'model_Aygo',
 'model_B 160',
 'model_B 180',
 'model_B 200',
 'model_B 220',
 'model_B 250',
 'model_B-Max',
 'model_B3',
 'model_B5',
 'model_B7',
 'model_BJ20',
 'model_BS4',
 'model_Baleno',
 'model_Bayon',
 'model_Beetle',
 'model_Bentayga',
 'model_Berlingo',
 'model_Bipper',
 'model_Birò',
 'model_Boxer',
 'model_Boxster',
 'model_Bravo',
 'model_C 180',
 'model_C 200',
 'model_C 220',
 'model_C 250',
 'model_C 300',
 'model_C 350',
 'model_C 400',
 'model_C 43 AMG',
 'model_C 63 AMG',
 'model_C-Elysée',
 'model_C-HR',
 'model_C-Max',
 'model_C-Zero',
 'model_C1',
 'model_C15',
 'model_C3',
 'model_C3 Aircross',
 'model_C3 Picasso',
 'model_C30',
 'model_C4',
 'model_C4 Aircross',
 'model_C4 Cactus',
 'model_C4 Picasso',
 'model_C4 SpaceTourer',
 'model_C5',
 'model_C5 Aircross',
 'model_C6',
 'model_C7',
 'model_C70',
 'model_C8',
 'model_CC',
 'model_CL 500',
 'model_CLA 180',
 'model_CLA 200',
 'model_CLA 220',
 'model_CLA 250',
 'model_CLA 45 AMG',
 'model_CLC',
 'model_CLS',
 'model_CLS 220',
 'model_CLS 250',
 'model_CLS 350',
 'model_CLS 400',
 'model_CLS 450',
 'model_CLS 500',
 'model_CLS 63 AMG',
 'model_CR-V',
 'model_CR-Z',
 'model_CT 200h',
 'model_CTS',
 'model_CX-3',
 'model_CX-30',
 'model_CX-5',
 'model_CX-7',
 'model_Caddy',
 'model_Caliber',
 'model_Camaro',
 'model_Camry',
 'model_Captiva',
 'model_Captur',
 'model_Carens',
 'model_Carnival',
 'model_Cascada',
 'model_Cayenne',
 'model_Cayman',
 "model_Ceed / cee'd",
 "model_Ceed SW / cee'd SW",
 'model_Celerio',
 'model_Challenger',
 'model_Charade',
 'model_Charger',
 'model_Cherokee',
 'model_Citan',
 'model_Citigo',
 'model_City',
 'model_Civic',
 'model_Clio',
 'model_Clubvan',
 'model_Colt',
 'model_Combo',
 'model_Compass',
 'model_Continental',
 'model_Cooper',
 'model_Cooper Cabrio',
 'model_Cooper Clubman',
 'model_Cooper Countryman',
 'model_Cooper Coupe',
 'model_Cooper D',
 'model_Cooper D Cabrio',
 'model_Cooper D Clubman',
 'model_Cooper D Countryman',
 'model_Cooper D Paceman',
 'model_Cooper Paceman',
 'model_Cooper Roadster',
 'model_Cooper S',
 'model_Cooper S Cabrio',
 'model_Cooper S Clubman',
 'model_Cooper S Countryman',
 'model_Cooper S Coupe',
 'model_Cooper S Paceman',
 'model_Cooper S Roadster',
 'model_Cooper SD',
 'model_Cooper SD Cabrio',
 'model_Cooper SD Clubman',
 'model_Cooper SD Countryman',
 'model_Cooper SD Coupe',
 'model_Cooper SD Paceman',
 'model_Cooper SE',
 'model_Corolla',
 'model_Corsa',
 'model_Crafter',
 'model_Cross Golf',
 'model_Cross Touran',
 'model_Crossland',
 'model_Crossland X',
 'model_Cruze',
 'model_Cuore',
 'model_D-Max',
 'model_D2S',
 'model_D3',
 'model_DS3',
 'model_DS4',
 'model_DS5',
 'model_Daily',
 'model_Dart',
 'model_Delta',
 'model_Doblo',
 'model_Dokker',
 'model_Ducato',
 'model_Due',
 'model_Durango',
 'model_Duster',
 'model_E 200',
 'model_E 220',
 'model_E 250',
 'model_E 300',
 'model_E 350',
 'model_E 400',
 'model_E 43 AMG',
 'model_E 450',
 'model_E 500',
 'model_E 53 AMG',
 'model_E 63 AMG',
 'model_E-NV200',
 'model_E-Pace',
 'model_EQC 400',
 'model_EQV 300',
 'model_ES 300',
 'model_EX30',
 'model_Eclipse',
 'model_Eclipse Cross',
 'model_EcoSport',
 'model_Edge',
 'model_Enyaq',
 'model_Eos',
 'model_Espace',
 'model_Evalia',
 'model_Exeo',
 'model_Expert',
 'model_Explorer',
 'model_Express',
 'model_F 150',
 'model_F-Pace',
 'model_F-Type',
 'model_F8 Tributo',
 'model_FF',
 'model_Fabia',
 'model_Fiesta',
 'model_Fiorino',
 'model_Flex',
 'model_Flying Spur',
 'model_Focus',
 'model_Forester',
 'model_Formentor',
 'model_Fox',
 'model_Freemont',
 'model_Fullback',
 'model_Fusion',
 'model_G',
 'model_G 350',
 'model_G 400',
 'model_G 500',
 'model_G 63 AMG',
 'model_GL 350',
 'model_GL 63 AMG',
 'model_GLA 180',
 'model_GLA 200',
 'model_GLA 220',
 'model_GLA 250',
 'model_GLA 45 AMG',
 'model_GLB 180',
 'model_GLB 200',
 'model_GLB 220',
 'model_GLB 250',
 'model_GLC 200',
 'model_GLC 220',
 'model_GLC 250',
 'model_GLC 300',
 'model_GLC 350',
 'model_GLC 43 AMG',
 'model_GLC 63 AMG',
 'model_GLE 250',
 'model_GLE 350',
 'model_GLE 400',
 'model_GLE 43 AMG',
 'model_GLE 450',
 'model_GLE 500',
 'model_GLE 63 AMG',
 'model_GLK 200',
 'model_GLK 220',
 'model_GLK 250',
 'model_GLK 350',
 'model_GLS 350',
 'model_GLS 400',
 'model_GLS 500',
 'model_GLS 600',
 'model_GS 250',
 'model_GS 450h',
 'model_GT',
 'model_GT86',
 'model_Galaxy',
 'model_Gallardo',
 'model_Genesis',
 'model_Getz',
 'model_Ghibli',
 'model_Ghost',
 'model_Gladiator',
 'model_Glory 580',
 'model_Golf',
 'model_Golf Cabriolet',
 'model_Golf GTE',
 'model_Golf GTI',
 'model_Golf Plus',
 'model_Golf Sportsvan',
 'model_Golf Variant',
 'model_GranCabrio',
 'model_GranTurismo',
 'model_Grand C-Max',
 'model_Grand C4 Picasso',
 'model_Grand C4 SpaceTourer',
 'model_Grand Caravan',
 'model_Grand Cherokee',
 'model_Grand Espace',
 'model_Grand Modus',
 'model_Grand Santa Fe',
 'model_Grand Scenic',
 'model_Grand Tourneo',
 'model_Grand Vitara',
 'model_Grand Voyager',
 'model_Grande Punto',
 'model_Grandland X',
 'model_Granta',
 'model_H-1',
 'model_HR-V',
 'model_Highlander',
 'model_Hilux',
 'model_Huracan',
 'model_I-MiEV',
 'model_I-Pace',
 'model_ID.3',
 'model_ID.4',
 'model_IS 300',
 'model_Ibiza',
 'model_Ignis',
 'model_Impreza',
 'model_Insight',
 'model_Insignia',
 'model_Ioniq',
 'model_JS 50',
 'model_Jazz',
 'model_Jetta',
 'model_Jimny',
 'model_John Cooper Works',
 'model_John Cooper Works Clubman',
 'model_John Cooper Works Countryman',
 'model_John Cooper Works Coupe',
 'model_Journey',
 'model_Juke',
 'model_Jumper',
 'model_Jumpy',
 'model_Ka/Ka+',
 'model_Kadjar',
 'model_Kalina',
 'model_Kamiq',
 'model_Kangoo',
 'model_Kangoo Z.E.',
 'model_Karl',
 'model_Karma',
 'model_Karoq',
 'model_Kizashi',
 'model_Kodiaq',
 'model_Koleos',
 'model_Kona',
 'model_Kona Elektro',
 'model_Korando',
 'model_Kuga',
 'model_LC 500',
 'model_LS 500',
 'model_LS 600',
 'model_LX 570',
 'model_Laguna',
 'model_Lancer',
 'model_Land Cruiser',
 'model_Landwind',
 'model_Latitude',
 'model_Leaf',
 'model_Legacy',
 'model_Leon',
 'model_Levante',
 'model_Levorg',
 'model_Linea',
 'model_Lodgy',
 'model_Logan',
 'model_M.Go',
 'model_M1',
 'model_M2',
 'model_M3',
 'model_M4',
 'model_M5',
 'model_M6',
 'model_M8',
 'model_M850',
 'model_ML 250',
 'model_ML 300',
 'model_ML 350',
 'model_MP4-12C',
 'model_MUSA',
 'model_MUSSO',
 'model_MX-30',
 'model_MX-5',
 'model_Macan',
 'model_Malibu',
 'model_Marco Polo',
 'model_Martin',
 'model_Martin DB11',
 'model_Martin DBX',
 'model_Martin Rapide',
 'model_Martin V8',
 'model_Martin Vantage',
 'model_Master',
 'model_Megane',
 'model_Meriva',
 'model_Micra',
 'model_Mii',
 'model_Mirai',
 'model_Model 3',
 'model_Model S',
 'model_Model X',
 'model_Modus',
 'model_Mokka',
 'model_Mokka X',
 'model_Mokka-E',
 'model_Mondeo',
 'model_Movano',
 'model_Mulsanne',
 'model_Murano',
 'model_Mustang',
 'model_NP300',
 'model_NSX',
 'model_NV200',
 'model_NV250',
 'model_NV300',
 'model_NX 300',
 'model_Navara',
 'model_Nemo',
 'model_New Beetle',
 'model_New Panda',
 'model_Niro',
 'model_Niva',
 'model_Note',
 'model_OUTBACK',
 'model_Octavia',
 'model_Odyssey',
 'model_One',
 'model_One Cabrio',
 'model_One Clubman',
 'model_One Countryman',
 'model_One D',
 'model_One D Clubman',
 'model_One D Countryman',
 'model_Optima',
 'model_Orlando',
 'model_Outlander',
 'model_Pacifica',
 'model_Pajero',
 'model_Panamera',
 'model_Panda',
 'model_Partner',
 'model_Passat',
 'model_Passat Alltrack',
 'model_Passat CC',
 'model_Passat Variant',
 'model_Pathfinder',
 'model_Phaeton',
 'model_Picanto',
 'model_Pixo',
 'model_Polo',
 'model_Polo Cross',
 'model_Polo GTI',
 'model_Porter',
 'model_Praktik',
 'model_Primastar',
 'model_Priora',
 'model_Prius',
 'model_Prius+',
 "model_ProCeed / pro_cee'd",
 'model_Proace',
 'model_Pullman',
 'model_Pulsar',
 'model_Puma',
 'model_Punto',
 'model_Punto EVO',
 'model_Punto Evo',
 'model_Q2',
 'model_Q3',
 'model_Q30',
 'model_Q5',
 'model_Q50',
 'model_Q60',
 'model_Q7',
 'model_Q70',
 'model_Q8',
 'model_Qashqai',
 'model_Qashqai+2',
 'model_Quattroporte',
 'model_Qubo',
 'model_R 300',
 'model_R 350',
 'model_R8',
 'model_RAM',
 'model_RAV 4',
 'model_RC 300h',
 'model_RCZ',
 'model_REXTON',
 'model_RS',
 'model_RS Q3',
 'model_RS Q8',
 'model_RS3',
 'model_RS4',
 'model_RS5',
 'model_RS6',
 'model_RS7',
 'model_RX 450h',
 'model_Ranger',
 'model_Rapid',
 'model_Rapid/Spaceback',
 'model_Renegade',
 'model_Rifter',
 'model_Rio',
 'model_Roadster',
 'model_Rodius',
 'model_Romeo 159',
 'model_Romeo 4C',
 'model_Romeo Giulia',
 'model_Romeo Giulietta',
 'model_Romeo MiTo',
 'model_Romeo Quadrifoglio',
 'model_Romeo Sportwagon',
 'model_Romeo Stelvio',
 'model_Roomster',
 'model_Rover Defender',
 'model_Rover Discovery',
 'model_Rover Discovery Sport',
 'model_Rover Freelander',
 'model_Rover Range Rover',
 'model_Rover Range Rover Evoque',
 'model_Rover Range Rover Sport',
 'model_Rover Range Rover Velar',
 'model_S 350',
 'model_S 400',
 'model_S 450',
 'model_S 500',
 'model_S 560',
 'model_S 600',
 'model_S 63 AMG',
 'model_S-Max',
 'model_S1',
 'model_S3',
 'model_S4',
 'model_S40',
 'model_S5',
 'model_S6',
 'model_S60',
 'model_S60 Cross Country',
 'model_S7',
 'model_S8',
 'model_S80',
 'model_S90',
 'model_SL 350',
 'model_SL 500',
 'model_SLC 180',
 'model_SLC 200',
 'model_SLC 250',
 'model_SLC 300',
 'model_SLK 200',
 'model_SLK 250',
 'model_SLK 300',
 'model_SLS',
 'model_SQ5',
 'model_SQ7',
 'model_SQ8',
 'model_SX4',
 'model_SX4 S-Cross',
 'model_Sandero',
 'model_Santa Fe',
 'model_Scala',
 'model_Scenic',
 'model_Scirocco',
 'model_Scudo',
 'model_Sedici',
 'model_Senova X35',
 'model_Sharan',
 'model_Silverado',
 'model_Sirion',
 'model_Sorento',
 'model_Soul',
 'model_Space Star',
 'model_Spacetourer',
 'model_Spark',
 'model_Splash',
 'model_Sportage',
 'model_Sprinter',
 'model_Stinger',
 'model_Stonic',
 'model_Superb',
 'model_Supra',
 'model_Swace',
 'model_Swift',
 'model_T-Cross',
 'model_T-Roc',
 'model_T4 Allstar',
 'model_T5',
 'model_T5 California',
 'model_T5 Caravelle',
 'model_T5 Kombi',
 'model_T5 Multivan',
 'model_T5 Shuttle',
 'model_T5 Transporter',
 'model_T6 California',
 'model_T6 Caravelle',
 'model_T6 Kombi',
 'model_T6 Multivan',
 'model_T6 Transporter',
 'model_T6.1 California',
 'model_T6.1 Multivan',
 'model_T6.1 Transporter',
 'model_TT',
 'model_TT RS',
 'model_TTS',
 'model_Taiga',
 'model_Talento',
 'model_Talisman',
 'model_Tarraco',
 'model_Taycan',
 'model_Terios',
 'model_Thema',
 'model_Tiguan',
 'model_Tipo',
 'model_Tivoli',
 'model_Toledo',
 'model_Touareg',
 'model_Touran',
 'model_Tourneo',
 'model_Tourneo Connect',
 'model_Tourneo Courier',
 'model_Tourneo Custom',
 'model_Town & Country',
 'model_Trafic',
 'model_Transit',
 'model_Transit Bus',
 'model_Transit Connect',
 'model_Transit Courier',
 'model_Transit Custom',
 'model_Transporter',
 'model_Traveller',
 'model_Trax',
 'model_Trezia',
 'model_Tucson',
 'model_Twingo',
 'model_Twizy',
 'model_UX 200',
 'model_UX 250h',
 'model_Urban Cruiser',
 'model_Urus',
 'model_V 200',
 'model_V 220',
 'model_V 250',
 'model_V 300',
 'model_V40',
 'model_V40 Cross Country',
 'model_V50',
 'model_V60',
 'model_V60 Cross Country',
 'model_V70',
 'model_V90',
 'model_V90 Cross Country',
 'model_Veloster',
 'model_Venga',
 'model_Verso',
 'model_Verso-S',
 'model_Vesta',
 'model_Viano',
 'model_Viper',
 'model_Vitara',
 'model_Vito',
 'model_Vivaro',
 'model_Volt',
 'model_Voyager',
 'model_Wind',
 'model_Wraith',
 'model_Wrangler',
 'model_X-Trail',
 'model_X1',
 'model_X2',
 'model_X2 M',
 'model_X3',
 'model_X3 M',
 'model_X4',
 'model_X4 M',
 'model_X5',
 'model_X5 M',
 'model_X6',
 'model_X6 M',
 'model_X7',
 'model_X7 M',
 'model_XC40',
 'model_XC60',
 'model_XC70',
 'model_XC90',
 'model_XCeed',
 'model_XD3',
 'model_XE',
 'model_XF',
 'model_XJ',
 'model_XK',
 'model_XKR',
 'model_XLV',
 'model_XT4',
 'model_XV',
 'model_Yaris',
 'model_Yeti',
 'model_Ypsilon',
 'model_Z06',
 'model_Z4',
 'model_ZOE',
 'model_Zafira',
 'model_Zafira Life',
 'model_Zafira Tourer',
 'model_brabus',
 'model_city-coupé/city-cabrio',
 'model_e',
 'model_e-Niro',
 'model_e-tron',
 'model_forFour',
 'model_forTwo',
 'model_i10',
 'model_i20',
 'model_i3',
 'model_i30',
 'model_i40',
 'model_i8',
 'model_iOn',
 'model_iQ',
 'model_iX20',
 'model_iX35',
 'model_up!',
 'fuel_CNG',
 'fuel_Diesel',
 'fuel_Electric',
 'fuel_Electric/Diesel',
 'fuel_Electric/Gasoline',
 'fuel_Ethanol',
 'fuel_Gasoline',
 'fuel_Hydrogen',
 'fuel_LPG',
 'gear_Manual',
 'gear_Semi-automatic',
 'offerType_New',
 'offerType_Pre-registered',
 'offerType_Used']

In [96]:
dummies.head()

,mileage,price,year,make_Aixam,make_Alfa,make_Alpina,make_Alpine,make_Aston,make_Audi,make_BMW,...,fuel_Electric/Gasoline,fuel_Ethanol,fuel_Gasoline,fuel_Hydrogen,fuel_LPG,gear_Manual,gear_Semi-automatic,offerType_New,offerType_Pre-registered,offerType_Used
0,235000,6800,2011,False,False,False,False,False,False,True,...,False,False,False,False,False,True,False,False,False,True
1,92800,6877,2011,False,False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,True
2,149300,6900,2011,False,False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,True
3,96200,6950,2011,False,False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,True
4,156000,6950,2011,False,False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,True

In [97]:
X = dummies.drop(['price'],axis="columns")
X.head()

,mileage,year,make_Aixam,make_Alfa,make_Alpina,make_Alpine,make_Aston,make_Audi,make_BMW,make_Baic,...,fuel_Electric/Gasoline,fuel_Ethanol,fuel_Gasoline,fuel_Hydrogen,fuel_LPG,gear_Manual,gear_Semi-automatic,offerType_New,offerType_Pre-registered,offerType_Used
0,235000,2011,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,False,False,False,True
1,92800,2011,False,False,False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,True
2,149300,2011,False,False,False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,True
3,96200,2011,False,False,False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,True
4,156000,2011,False,False,False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,True

In [99]:
Y = dummies.price
Y.head()

0    6800
1    6877
2    6900
3    6950
4    6950
Name: price, dtype: int64

In [100]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size=0.2, random_state=10)

In [114]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)
model.score(X_test,y_test)

0.8350631565975243

In [103]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score

cv = ShuffleSplit(n_splits=10, test_size=0.2, random_state=0)
cross_val_score(LinearRegression(), X,Y,cv=cv)

array([ 8.18948083e-01,  7.98890959e-01, -5.60401548e+07,  8.69354386e-01,
        8.71198172e-01,  8.67169765e-01, -1.26214854e+09, -7.30216252e+06,
        8.14357115e-01,  8.14077577e-01])

In [108]:
X.columns.tolist()

['mileage',
 'year',
 'make_Aixam',
 'make_Alfa',
 'make_Alpina',
 'make_Alpine',
 'make_Aston',
 'make_Audi',
 'make_BMW',
 'make_Baic',
 'make_Bentley',
 'make_Brilliance',
 'make_Cadillac',
 'make_Chevrolet',
 'make_Chrysler',
 'make_Citroen',
 'make_Corvette',
 'make_Cupra',
 'make_DFSK',
 'make_DS',
 'make_Dacia',
 'make_Daihatsu',
 'make_Dodge',
 'make_Estrima',
 'make_FISKER',
 'make_Ferrari',
 'make_Fiat',
 'make_Ford',
 'make_Honda',
 'make_Hyundai',
 'make_Infiniti',
 'make_Isuzu',
 'make_Iveco',
 'make_Jaguar',
 'make_Jeep',
 'make_Kia',
 'make_Lada',
 'make_Lamborghini',
 'make_Lancia',
 'make_Land',
 'make_Lexus',
 'make_Ligier',
 'make_MINI',
 'make_Maserati',
 'make_Maybach',
 'make_Mazda',
 'make_McLaren',
 'make_Mercedes-Benz',
 'make_Microcar',
 'make_Mitsubishi',
 'make_Morgan',
 'make_Nissan',
 'make_Opel',
 'make_Others',
 'make_Peugeot',
 'make_Piaggio',
 'make_Polestar',
 'make_Porsche',
 'make_RAM',
 'make_Renault',
 'make_Rolls-Royce',
 'make_SEAT',
 'make_Skoda',
 'make_SsangYong',
 'make_Subaru',
 'make_Suzuki',
 'make_Tesla',
 'make_Toyota',
 'make_Volkswagen',
 'make_Volvo',
 'make_Zhidou',
 'make_smart',
 'model_108',
 'model_114',
 'model_116',
 'model_118',
 'model_120',
 'model_123',
 'model_124 Spider',
 'model_125',
 'model_135',
 'model_140',
 'model_1500',
 'model_2',
 'model_2008',
 'model_206',
 'model_207',
 'model_208',
 'model_214',
 'model_216',
 'model_218',
 'model_220',
 'model_225',
 'model_230',
 'model_240',
 'model_250',
 'model_3',
 'model_3-Wheeler',
 'model_300',
 'model_3008',
 'model_300C',
 'model_301',
 'model_308',
 'model_316',
 'model_318',
 'model_320',
 'model_323',
 'model_325',
 'model_328',
 'model_330',
 'model_335',
 'model_340',
 'model_370Z',
 'model_4008',
 'model_407',
 'model_418',
 'model_420',
 'model_428',
 'model_430',
 'model_435',
 'model_440',
 'model_458',
 'model_488',
 'model_5',
 'model_500',
 'model_5008',
 'model_500C',
 'model_500L',
 'model_500X',
 'model_500e',
 'model_508',
 'model_518',
 'model_520',
 'model_523',
 'model_525',
 'model_528',
 'model_530',
 'model_535',
 'model_540',
 'model_550',
 'model_570S',
 'model_595',
 'model_595 Competizione',
 'model_595 Turismo',
 'model_595C',
 'model_6',
 'model_600LT',
 'model_630',
 'model_640',
 'model_650',
 'model_675LT',
 'model_695',
 'model_720S',
 'model_730',
 'model_740',
 'model_750',
 'model_760',
 'model_807',
 'model_812',
 'model_840',
 'model_911',
 'model_991',
 'model_992',
 'model_997',
 'model_A 160',
 'model_A 180',
 'model_A 200',
 'model_A 220',
 'model_A 250',
 'model_A 35 AMG',
 'model_A 45 AMG',
 'model_A1',
 'model_A110',
 'model_A3',
 'model_A4',
 'model_A4 allroad',
 'model_A5',
 'model_A6',
 'model_A6 allroad',
 'model_A7',
 'model_A8',
 'model_AMG GT',
 'model_ASX',
 'model_ATS',
 'model_Accord',
 'model_Adam',
 'model_Agila',
 'model_Alaskan',
 'model_Alhambra',
 'model_Alpine A110',
 'model_Altea',
 'model_Altea XL',
 'model_Alto',
 'model_Amarok',
 'model_Ampera',
 'model_Antara',
 'model_Ape',
 'model_Arkana',
 'model_Arona',
 'model_Arteon',
 'model_Aspen',
 'model_Astra',
 'model_Ateca',
 'model_Auris',
 'model_Automobiles DS 3',
 'model_Automobiles DS 3 Crossback',
 'model_Automobiles DS 4',
 'model_Automobiles DS 5',
 'model_Automobiles DS 7 Crossback',
 'model_Avensis',
 'model_Aventador',
 'model_Aveo',
 'model_Aygo',
 'model_B 160',
 'model_B 180',
 'model_B 200',
 'model_B 220',
 'model_B 250',
 'model_B-Max',
 'model_B3',
 'model_B5',
 'model_B7',
 'model_BJ20',
 'model_BS4',
 'model_Baleno',
 'model_Bayon',
 'model_Beetle',
 'model_Bentayga',
 'model_Berlingo',
 'model_Bipper',
 'model_Birò',
 'model_Boxer',
 'model_Boxster',
 'model_Bravo',
 'model_C 180',
 'model_C 200',
 'model_C 220',
 'model_C 250',
 'model_C 300',
 'model_C 350',
 'model_C 400',
 'model_C 43 AMG',
 'model_C 63 AMG',
 'model_C-Elysée',
 'model_C-HR',
 'model_C-Max',
 'model_C-Zero',
 'model_C1',
 'model_C15',
 'model_C3',
 'model_C3 Aircross',
 'model_C3 Picasso',
 'model_C30',
 'model_C4',
 'model_C4 Aircross',
 'model_C4 Cactus',
 'model_C4 Picasso',
 'model_C4 SpaceTourer',
 'model_C5',
 'model_C5 Aircross',
 'model_C6',
 'model_C7',
 'model_C70',
 'model_C8',
 'model_CC',
 'model_CL 500',
 'model_CLA 180',
 'model_CLA 200',
 'model_CLA 220',
 'model_CLA 250',
 'model_CLA 45 AMG',
 'model_CLC',
 'model_CLS',
 'model_CLS 220',
 'model_CLS 250',
 'model_CLS 350',
 'model_CLS 400',
 'model_CLS 450',
 'model_CLS 500',
 'model_CLS 63 AMG',
 'model_CR-V',
 'model_CR-Z',
 'model_CT 200h',
 'model_CTS',
 'model_CX-3',
 'model_CX-30',
 'model_CX-5',
 'model_CX-7',
 'model_Caddy',
 'model_Caliber',
 'model_Camaro',
 'model_Camry',
 'model_Captiva',
 'model_Captur',
 'model_Carens',
 'model_Carnival',
 'model_Cascada',
 'model_Cayenne',
 'model_Cayman',
 "model_Ceed / cee'd",
 "model_Ceed SW / cee'd SW",
 'model_Celerio',
 'model_Challenger',
 'model_Charade',
 'model_Charger',
 'model_Cherokee',
 'model_Citan',
 'model_Citigo',
 'model_City',
 'model_Civic',
 'model_Clio',
 'model_Clubvan',
 'model_Colt',
 'model_Combo',
 'model_Compass',
 'model_Continental',
 'model_Cooper',
 'model_Cooper Cabrio',
 'model_Cooper Clubman',
 'model_Cooper Countryman',
 'model_Cooper Coupe',
 'model_Cooper D',
 'model_Cooper D Cabrio',
 'model_Cooper D Clubman',
 'model_Cooper D Countryman',
 'model_Cooper D Paceman',
 'model_Cooper Paceman',
 'model_Cooper Roadster',
 'model_Cooper S',
 'model_Cooper S Cabrio',
 'model_Cooper S Clubman',
 'model_Cooper S Countryman',
 'model_Cooper S Coupe',
 'model_Cooper S Paceman',
 'model_Cooper S Roadster',
 'model_Cooper SD',
 'model_Cooper SD Cabrio',
 'model_Cooper SD Clubman',
 'model_Cooper SD Countryman',
 'model_Cooper SD Coupe',
 'model_Cooper SD Paceman',
 'model_Cooper SE',
 'model_Corolla',
 'model_Corsa',
 'model_Crafter',
 'model_Cross Golf',
 'model_Cross Touran',
 'model_Crossland',
 'model_Crossland X',
 'model_Cruze',
 'model_Cuore',
 'model_D-Max',
 'model_D2S',
 'model_D3',
 'model_DS3',
 'model_DS4',
 'model_DS5',
 'model_Daily',
 'model_Dart',
 'model_Delta',
 'model_Doblo',
 'model_Dokker',
 'model_Ducato',
 'model_Due',
 'model_Durango',
 'model_Duster',
 'model_E 200',
 'model_E 220',
 'model_E 250',
 'model_E 300',
 'model_E 350',
 'model_E 400',
 'model_E 43 AMG',
 'model_E 450',
 'model_E 500',
 'model_E 53 AMG',
 'model_E 63 AMG',
 'model_E-NV200',
 'model_E-Pace',
 'model_EQC 400',
 'model_EQV 300',
 'model_ES 300',
 'model_EX30',
 'model_Eclipse',
 'model_Eclipse Cross',
 'model_EcoSport',
 'model_Edge',
 'model_Enyaq',
 'model_Eos',
 'model_Espace',
 'model_Evalia',
 'model_Exeo',
 'model_Expert',
 'model_Explorer',
 'model_Express',
 'model_F 150',
 'model_F-Pace',
 'model_F-Type',
 'model_F8 Tributo',
 'model_FF',
 'model_Fabia',
 'model_Fiesta',
 'model_Fiorino',
 'model_Flex',
 'model_Flying Spur',
 'model_Focus',
 'model_Forester',
 'model_Formentor',
 'model_Fox',
 'model_Freemont',
 'model_Fullback',
 'model_Fusion',
 'model_G',
 'model_G 350',
 'model_G 400',
 'model_G 500',
 'model_G 63 AMG',
 'model_GL 350',
 'model_GL 63 AMG',
 'model_GLA 180',
 'model_GLA 200',
 'model_GLA 220',
 'model_GLA 250',
 'model_GLA 45 AMG',
 'model_GLB 180',
 'model_GLB 200',
 'model_GLB 220',
 'model_GLB 250',
 'model_GLC 200',
 'model_GLC 220',
 'model_GLC 250',
 'model_GLC 300',
 'model_GLC 350',
 'model_GLC 43 AMG',
 'model_GLC 63 AMG',
 'model_GLE 250',
 'model_GLE 350',
 'model_GLE 400',
 'model_GLE 43 AMG',
 'model_GLE 450',
 'model_GLE 500',
 'model_GLE 63 AMG',
 'model_GLK 200',
 'model_GLK 220',
 'model_GLK 250',
 'model_GLK 350',
 'model_GLS 350',
 'model_GLS 400',
 'model_GLS 500',
 'model_GLS 600',
 'model_GS 250',
 'model_GS 450h',
 'model_GT',
 'model_GT86',
 'model_Galaxy',
 'model_Gallardo',
 'model_Genesis',
 'model_Getz',
 'model_Ghibli',
 'model_Ghost',
 'model_Gladiator',
 'model_Glory 580',
 'model_Golf',
 'model_Golf Cabriolet',
 'model_Golf GTE',
 'model_Golf GTI',
 'model_Golf Plus',
 'model_Golf Sportsvan',
 'model_Golf Variant',
 'model_GranCabrio',
 'model_GranTurismo',
 'model_Grand C-Max',
 'model_Grand C4 Picasso',
 'model_Grand C4 SpaceTourer',
 'model_Grand Caravan',
 'model_Grand Cherokee',
 'model_Grand Espace',
 'model_Grand Modus',
 'model_Grand Santa Fe',
 'model_Grand Scenic',
 'model_Grand Tourneo',
 'model_Grand Vitara',
 'model_Grand Voyager',
 'model_Grande Punto',
 'model_Grandland X',
 'model_Granta',
 'model_H-1',
 'model_HR-V',
 'model_Highlander',
 'model_Hilux',
 'model_Huracan',
 'model_I-MiEV',
 'model_I-Pace',
 'model_ID.3',
 'model_ID.4',
 'model_IS 300',
 'model_Ibiza',
 'model_Ignis',
 'model_Impreza',
 'model_Insight',
 'model_Insignia',
 'model_Ioniq',
 'model_JS 50',
 'model_Jazz',
 'model_Jetta',
 'model_Jimny',
 'model_John Cooper Works',
 'model_John Cooper Works Clubman',
 'model_John Cooper Works Countryman',
 'model_John Cooper Works Coupe',
 'model_Journey',
 'model_Juke',
 'model_Jumper',
 'model_Jumpy',
 'model_Ka/Ka+',
 'model_Kadjar',
 'model_Kalina',
 'model_Kamiq',
 'model_Kangoo',
 'model_Kangoo Z.E.',
 'model_Karl',
 'model_Karma',
 'model_Karoq',
 'model_Kizashi',
 'model_Kodiaq',
 'model_Koleos',
 'model_Kona',
 'model_Kona Elektro',
 'model_Korando',
 'model_Kuga',
 'model_LC 500',
 'model_LS 500',
 'model_LS 600',
 'model_LX 570',
 'model_Laguna',
 'model_Lancer',
 'model_Land Cruiser',
 'model_Landwind',
 'model_Latitude',
 'model_Leaf',
 'model_Legacy',
 'model_Leon',
 'model_Levante',
 'model_Levorg',
 'model_Linea',
 'model_Lodgy',
 'model_Logan',
 'model_M.Go',
 'model_M1',
 'model_M2',
 'model_M3',
 'model_M4',
 'model_M5',
 'model_M6',
 'model_M8',
 'model_M850',
 'model_ML 250',
 'model_ML 300',
 'model_ML 350',
 'model_MP4-12C',
 'model_MUSA',
 'model_MUSSO',
 'model_MX-30',
 'model_MX-5',
 'model_Macan',
 'model_Malibu',
 'model_Marco Polo',
 'model_Martin',
 'model_Martin DB11',
 'model_Martin DBX',
 'model_Martin Rapide',
 'model_Martin V8',
 'model_Martin Vantage',
 'model_Master',
 'model_Megane',
 'model_Meriva',
 'model_Micra',
 'model_Mii',
 'model_Mirai',
 'model_Model 3',
 'model_Model S',
 'model_Model X',
 'model_Modus',
 'model_Mokka',
 'model_Mokka X',
 'model_Mokka-E',
 'model_Mondeo',
 'model_Movano',
 'model_Mulsanne',
 'model_Murano',
 'model_Mustang',
 'model_NP300',
 'model_NSX',
 'model_NV200',
 'model_NV250',
 'model_NV300',
 'model_NX 300',
 'model_Navara',
 'model_Nemo',
 'model_New Beetle',
 'model_New Panda',
 'model_Niro',
 'model_Niva',
 'model_Note',
 'model_OUTBACK',
 'model_Octavia',
 'model_Odyssey',
 'model_One',
 'model_One Cabrio',
 'model_One Clubman',
 'model_One Countryman',
 'model_One D',
 'model_One D Clubman',
 'model_One D Countryman',
 'model_Optima',
 'model_Orlando',
 'model_Outlander',
 'model_Pacifica',
 'model_Pajero',
 'model_Panamera',
 'model_Panda',
 'model_Partner',
 'model_Passat',
 'model_Passat Alltrack',
 'model_Passat CC',
 'model_Passat Variant',
 'model_Pathfinder',
 'model_Phaeton',
 'model_Picanto',
 'model_Pixo',
 'model_Polo',
 'model_Polo Cross',
 'model_Polo GTI',
 'model_Porter',
 'model_Praktik',
 'model_Primastar',
 'model_Priora',
 'model_Prius',
 'model_Prius+',
 "model_ProCeed / pro_cee'd",
 'model_Proace',
 'model_Pullman',
 'model_Pulsar',
 'model_Puma',
 'model_Punto',
 'model_Punto EVO',
 'model_Punto Evo',
 'model_Q2',
 'model_Q3',
 'model_Q30',
 'model_Q5',
 'model_Q50',
 'model_Q60',
 'model_Q7',
 'model_Q70',
 'model_Q8',
 'model_Qashqai',
 'model_Qashqai+2',
 'model_Quattroporte',
 'model_Qubo',
 'model_R 300',
 'model_R 350',
 'model_R8',
 'model_RAM',
 'model_RAV 4',
 'model_RC 300h',
 'model_RCZ',
 'model_REXTON',
 'model_RS',
 'model_RS Q3',
 'model_RS Q8',
 'model_RS3',
 'model_RS4',
 'model_RS5',
 'model_RS6',
 'model_RS7',
 'model_RX 450h',
 'model_Ranger',
 'model_Rapid',
 'model_Rapid/Spaceback',
 'model_Renegade',
 'model_Rifter',
 'model_Rio',
 'model_Roadster',
 'model_Rodius',
 'model_Romeo 159',
 'model_Romeo 4C',
 'model_Romeo Giulia',
 'model_Romeo Giulietta',
 'model_Romeo MiTo',
 'model_Romeo Quadrifoglio',
 'model_Romeo Sportwagon',
 'model_Romeo Stelvio',
 'model_Roomster',
 'model_Rover Defender',
 'model_Rover Discovery',
 'model_Rover Discovery Sport',
 'model_Rover Freelander',
 'model_Rover Range Rover',
 'model_Rover Range Rover Evoque',
 'model_Rover Range Rover Sport',
 'model_Rover Range Rover Velar',
 'model_S 350',
 'model_S 400',
 'model_S 450',
 'model_S 500',
 'model_S 560',
 'model_S 600',
 'model_S 63 AMG',
 'model_S-Max',
 'model_S1',
 'model_S3',
 'model_S4',
 'model_S40',
 'model_S5',
 'model_S6',
 'model_S60',
 'model_S60 Cross Country',
 'model_S7',
 'model_S8',
 'model_S80',
 'model_S90',
 'model_SL 350',
 'model_SL 500',
 'model_SLC 180',
 'model_SLC 200',
 'model_SLC 250',
 'model_SLC 300',
 'model_SLK 200',
 'model_SLK 250',
 'model_SLK 300',
 'model_SLS',
 'model_SQ5',
 'model_SQ7',
 'model_SQ8',
 'model_SX4',
 'model_SX4 S-Cross',
 'model_Sandero',
 'model_Santa Fe',
 'model_Scala',
 'model_Scenic',
 'model_Scirocco',
 'model_Scudo',
 'model_Sedici',
 'model_Senova X35',
 'model_Sharan',
 'model_Silverado',
 'model_Sirion',
 'model_Sorento',
 'model_Soul',
 'model_Space Star',
 'model_Spacetourer',
 'model_Spark',
 'model_Splash',
 'model_Sportage',
 'model_Sprinter',
 'model_Stinger',
 'model_Stonic',
 'model_Superb',
 'model_Supra',
 'model_Swace',
 'model_Swift',
 'model_T-Cross',
 'model_T-Roc',
 'model_T4 Allstar',
 'model_T5',
 'model_T5 California',
 'model_T5 Caravelle',
 'model_T5 Kombi',
 'model_T5 Multivan',
 'model_T5 Shuttle',
 'model_T5 Transporter',
 'model_T6 California',
 'model_T6 Caravelle',
 'model_T6 Kombi',
 'model_T6 Multivan',
 'model_T6 Transporter',
 'model_T6.1 California',
 'model_T6.1 Multivan',
 'model_T6.1 Transporter',
 'model_TT',
 'model_TT RS',
 'model_TTS',
 'model_Taiga',
 'model_Talento',
 'model_Talisman',
 'model_Tarraco',
 'model_Taycan',
 'model_Terios',
 'model_Thema',
 'model_Tiguan',
 'model_Tipo',
 'model_Tivoli',
 'model_Toledo',
 'model_Touareg',
 'model_Touran',
 'model_Tourneo',
 'model_Tourneo Connect',
 'model_Tourneo Courier',
 'model_Tourneo Custom',
 'model_Town & Country',
 'model_Trafic',
 'model_Transit',
 'model_Transit Bus',
 'model_Transit Connect',
 'model_Transit Courier',
 'model_Transit Custom',
 'model_Transporter',
 'model_Traveller',
 'model_Trax',
 'model_Trezia',
 'model_Tucson',
 'model_Twingo',
 'model_Twizy',
 'model_UX 200',
 'model_UX 250h',
 'model_Urban Cruiser',
 'model_Urus',
 'model_V 200',
 'model_V 220',
 'model_V 250',
 'model_V 300',
 'model_V40',
 'model_V40 Cross Country',
 'model_V50',
 'model_V60',
 'model_V60 Cross Country',
 'model_V70',
 'model_V90',
 'model_V90 Cross Country',
 'model_Veloster',
 'model_Venga',
 'model_Verso',
 'model_Verso-S',
 'model_Vesta',
 'model_Viano',
 'model_Viper',
 'model_Vitara',
 'model_Vito',
 'model_Vivaro',
 'model_Volt',
 'model_Voyager',
 'model_Wind',
 'model_Wraith',
 'model_Wrangler',
 'model_X-Trail',
 'model_X1',
 'model_X2',
 'model_X2 M',
 'model_X3',
 'model_X3 M',
 'model_X4',
 'model_X4 M',
 'model_X5',
 'model_X5 M',
 'model_X6',
 'model_X6 M',
 'model_X7',
 'model_X7 M',
 'model_XC40',
 'model_XC60',
 'model_XC70',
 'model_XC90',
 'model_XCeed',
 'model_XD3',
 'model_XE',
 'model_XF',
 'model_XJ',
 'model_XK',
 'model_XKR',
 'model_XLV',
 'model_XT4',
 'model_XV',
 'model_Yaris',
 'model_Yeti',
 'model_Ypsilon',
 'model_Z06',
 'model_Z4',
 'model_ZOE',
 'model_Zafira',
 'model_Zafira Life',
 'model_Zafira Tourer',
 'model_brabus',
 'model_city-coupé/city-cabrio',
 'model_e',
 'model_e-Niro',
 'model_e-tron',
 'model_forFour',
 'model_forTwo',
 'model_i10',
 'model_i20',
 'model_i3',
 'model_i30',
 'model_i40',
 'model_i8',
 'model_iOn',
 'model_iQ',
 'model_iX20',
 'model_iX35',
 'model_up!',
 'fuel_CNG',
 'fuel_Diesel',
 'fuel_Electric',
 'fuel_Electric/Diesel',
 'fuel_Electric/Gasoline',
 'fuel_Ethanol',
 'fuel_Gasoline',
 'fuel_Hydrogen',
 'fuel_LPG',
 'gear_Manual',
 'gear_Semi-automatic',
 'offerType_New',
 'offerType_Pre-registered',
 'offerType_Used']

In [149]:
def get_the_index(df,col_name,col_value):
    index = np.where(df.columns == col_name + '_' + col_value)
    if index[0].size == 0:
        return -1
    else:
        return index[0][0]


def predict_car_price(mileage,year,make,model,fuel, gear,offerType):
    make_index = get_the_index(X, 'make',make)
    model_index = get_the_index(X, 'model',model)
    fuel_index = get_the_index(X, 'fuel',fuel)
    gear_index = get_the_index(X, 'gear',gear)
    offerType_index = get_the_index(X, 'offerType',offerType)
    x = np.zeros(len(X.columns))
    x[0] = mileage
    x[1] = year
    if make_index >=0:
        x[make_index] = 1
    if model_index >=0:
        x[model_index] = 1
    if fuel_index >= 0:
        x[fuel_index] = 1        
    if gear_index >=0:
        x[gear_index] = 1
    if offerType_index >=0:
        x[offerType_index] = 1    
    return x

In [150]:
xv = predict_car_price(50000, 2020,'BMW','M5','Gasoline','Manual','Used')

In [151]:
model.predict([xv])[0]

/opt/anaconda3/envs/car-price-prediction/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

49050.604487264995

In [152]:
import json
columns = {
    'data_columns' : [col.lower() for col in X.columns]
}
with open("columns.json","w") as f:
    f.write(json.dumps(columns))

In [153]:
import pickle
with open('car_price_prediction.pickle','wb') as f:
    pickle.dump(model,f)